const GRAY_COLOR = '#DBDAD7';
const MUSTARD_COLOR = '#D1B64C';
const YELLOW_COLOR = '#FEDA2F';
const BROWN_COLOR = '#645546';
const RED_COLOR = '#A62C2A';

export const colorsApp = {
  GRAY_COLOR,
  MUSTARD_COLOR,
  YELLOW_COLOR,
  BROWN_COLOR,
  RED_COLOR,
};
